name: Rust CI with Local Docker Build

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - develop
  pull_request:   
    branches:
      - main
      - develop

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Build Docker image
      run: docker build -t element-packet-forwarder-docker ${GITHUB_WORKSPACE}

    - name: Build and Test
      run: |
        docker run -v ${GITHUB_WORKSPACE}:/prj element-packet-forwarder-docker cargo build --verbose
        docker run -v ${GITHUB_WORKSPACE}:/prj element-packet-forwarder-docker cargo test --verbose
        sudo chown -R $(id -u):$(id -g) ${GITHUB_WORKSPACE}
    - name: Clippy Check
      uses: actions-rs/clippy-check@v1
      with:
          token: ${{ secrets.GITHUB_TOKEN }}
          args: --all-features