name: Rust CI with Local Docker Build

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Build Docker image
      run: docker build -t element-packet-forwarder-docker ${GITHUB_WORKSPACE}

    - name: Build and Test
      run: |
        docker run element-packet-forwarder-docker cargo build --verbose
        docker run element-packet-forwarder-docker cargo test --verbose